config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :collections
    resources :designers
    resources :games
    resources :libraries
    resources :players

    root to: "games#index"
  end

  resources :collections do
    resources :games
  end

  resources :designers do
    resources :games
  end

  resources :games

  resources :players do
    resources :collections
    resources :games
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "libraries#index"
end

app/models/designer.rb
# This model represents a game designer
class Designer < ApplicationRecord
  has_many :games, dependent: :destroy

  validates :name, uniqueness: true # rubocop:disable Rails/UniqueValidationWithoutIndex
  validates :website, url: { allow_nil: true }
end

app/controllers/admin/designers_controller.rb
module Admin
  class DesignersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/designers_controller.rb
# This controller is responsible for managing game designers
class DesignersController < ApplicationController
  before_action :set_designer, only: %i[show edit update destroy]

  # GET /designers or /designers.json
  def index
    @designers = Designer.all
  end

  # GET /designers/1 or /designers/1.json
  def show; end

  # GET /designers/new
  def new
    @designer = Designer.new
  end

  # GET /designers/1/edit
  def edit; end

  # POST /designers or /designers.json
  def create
    @designer = Designer.new(designer_params)

    respond_to do |format|
      if @designer.save
        format.html { redirect_to designer_url(@designer), notice: notice_t(@designer, :create) }
        format.json { render :show, status: :created, location: @designer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designers/1 or /designers/1.json
  def update
    respond_to do |format|
      if @designer.update(designer_params)
        format.html { redirect_to designer_url(@designer), notice: notice_t(@designer, :update) }
        format.json { render :show, status: :ok, location: @designer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designers/1 or /designers/1.json
  def destroy
    @designer.destroy!

    respond_to do |format|
      format.html { redirect_to designers_url, notice: notice_t(@designer, :delete) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_designer
    @designer = Designer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def designer_params
    params.require(:designer).permit(:name, :website)
  end
end

app/helpers/designers_helper.rb
# Helper methods for game designers
module DesignersHelper
end

app/views/designers/_designer.html.erb
<div id="<%= dom_id designer %>">
  <p>
    <strong>Name:</strong>
    <%= designer.name %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= designer.website %>
  </p>

</div>

app/views/designers/_form.html.erb
<%= form_with(model: designer) do |form| %>
  <% if designer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(designer.errors.count, "error") %> prohibited this designer from being saved:</h2>

      <ul>
        <% designer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/designers/edit.html.erb
<h1>Editing designer</h1>

<%= render "form", designer: @designer %>

<br>

<div>
  <%= link_to "Show this designer", @designer %> |
  <%= link_to "Back to designers", designers_path %>
</div>

app/views/designers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Designers</h1>

<div id="designers">
  <% @designers.each do |designer| %>
    <%= render designer %>
    <p>
      <%= link_to "Show this designer", designer %>
    </p>
  <% end %>
</div>

<%= link_to "New designer", new_designer_path %>

app/views/designers/new.html.erb
<h1>New designer</h1>

<%= render "form", designer: @designer %>

<br>

<div>
  <%= link_to "Back to designers", designers_path %>
</div>

app/views/designers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @designer %>

<div>
  <%= link_to "Edit this designer", edit_designer_path(@designer) %> |
  <%= link_to "Back to designers", designers_path %>

  <%= button_to "Destroy this designer", @designer, method: :delete %>
</div>